version: '3'

services:

  #mysql docker container for catalogue service
  db-abstract-projections:
    container_name: db-abstract-projections
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password@App22
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - '3309:3306'
  #catalogue service
  abstract-projections:
    container_name: abstract-projections
    image: murethi/abstract-projections
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-abstract-projections:3306/test_db
    depends_on:
      - db-abstract-projections
