server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test_db
    username: kodix
    password: Kodix#2022
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: user-service
