server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://db-abstract-projections:3306/test_db
    username: test_user
    password: password@App22
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: abstract-projections
